services:
  ollama-service:
    image: deepseek-v3:latest
    runtime: nvidia
    environment:
      - OLLAMA_ORIGINS="*"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_CAPABILITIES=all
    ports:
      - 11434:11434
    entrypoint: ["/bin/bash", "/scripts/start_ollama.sh"]
    volumes:
      - ./ollama:/root/.ollama
      - ./scripts:/scripts
  ui:
    image: ghcr.io/open-webui/open-webui:latest
    ports:
      - 9783:8080
    volumes:
      - ./open-webui:/app/backend/data
networks:
  chat-ui:
    driver: bridge